backend: cmd
working_dir: .reme

metadata:
  context_window_tokens: 100000
  reserve_tokens: 30000
  keep_recent_tokens: 10000
  vector_weight: 0.7
  candidate_multiplier: 2

llms:
  default:
    backend: openai
    model_name: qwen3-235b-a22b-thinking-2507
    request_interval: 1

embedding_models:
  default:
    backend: openai
    model_name: text-embedding-v4
    dimensions: 1024

memory_stores:
  default:
#    backend: chroma
    backend: local
    db_name: reme.db
    store_name: reme
    embedding_model: default
    fts_enabled: true
    vector_enabled: true

file_watchers:
  default:
    backend: full
    memory_store: default
    watch_paths: [".reme", ".reme/memory"]
    suffix_filters: [".md"]
    recursive: false
    scan_on_start: true

token_counters:
  default:
    backend: base

  hf:
    backend: hf
    model_name: Qwen/Qwen3-Coder-30B-A3B-Instruct
    use_mirror: true
